version: '2'
services:
    cache-app:
        image: cache
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cache-mysql:3306/cache?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cache-mysql:
        extends:
            file: mysql.yml
            service: cache-mysql
